name: MicrosservicesNewCI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: DEV
      url: 'microsservice.com.br'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy dev
        
  deploy-hml:
    runs-on: ubuntu-latest
    environment:
      name: HML
      url: 'microsservice.com.br'
    needs: deploy-dev
    steps:
      - name: Run a one-line script
        run: echo Deploy hml
        
  deploy-prd:
    runs-on: ubuntu-latest
    environment:
      name: PRD
      url: 'microsservice.com.br'
    needs: deploy-hml
    steps:
      - name: Run a one-line script
        run: echo Deploy prd


